    <p class="btn-sp"><span class="icon-menu"></span></p>
    <div class="l-navi__sp">
      <h2>メンバー</h2>
      <ul class="l-navi__list">
        <li class="l-navi__item"><a href="/portfolio/member/kfukuda">福田&nbsp;和彦</a></li>
        <li class="l-navi__item"><a href="/portfolio/member/eokawachi">大川内&nbsp;絵里</a></li>
        <li class="l-navi__item"><a href="/portfolio/member/myoshida">吉田&nbsp;恵</a></li>
        <li class="l-navi__item"><a href="/portfolio/member/yumeno">梅野&nbsp;有希</a></li>
        <li class="l-navi__item"><a href="/portfolio/member/mohta">太田&nbsp;実玖</a></li>
      </ul>
    </div>
    <div class="overlay-sp"></div>