  <footer class="l-footer">

    <p class="fnavi"><a href="#ScrollTOP" class="fa fa-angle-up"></a></p>
    <div class="l-footer__body">

      <div class="l-footer__item">
        <ul class="l-footer__list">
          <li class="l-footer__list__item">
            <a href="https://ewm.co.jp/" class="l-footer__list__link" target="_blank">運営会社</a>
          </li>
          <li class="l-footer__list__item">
            <a href="https://ewm.co.jp/contact/" class="l-footer__list__link" target="_blank">お問い合わせ</a>
          </li>
        </ul>
        <!-- l-footer__list -->
      </div>
      <!-- l-footer__item -->

      <div class="l-footer__item">
        <p class="copy">&copy;2020 EWM Group</p>
      </div>
      <!-- l-footer__item -->

    </div>
    <!-- l-footer__body -->
  </footer>
  <!-- l-footer -->