<meta name="viewport" content="width=device-width, initial-scale=1.0">
<!-- favicon -->
<link rel="icon" href="/portfolio/common/img/favicon/favicon.ico" />
<!-- SP icon -->
<link rel="apple-touch-icon" sizes="180x180" href="/portfolio/common/img/favicon/sp-icon.png" />
<!-- Web font -->
<link href="https://fonts.googleapis.com/css?family=Lato:400,700,900|Raleway:300,400,500,600,700" rel="stylesheet">
<!-- stylesheet -->
<link rel="stylesheet" type="text/css" href="/portfolio/common/css/jquery.datetimepicker.css" media="all" />
<link rel="stylesheet" type="text/css" href="/portfolio/common/css/magnific-popup.css" media="all" />
<link rel="stylesheet" type="text/css" href="/portfolio/common/css/common.css" media="all" />