<script type="text/javascript" src="/portfolio/common/js/jquery-2.2.0.min.js"></script>
<script type="text/javascript" src="/portfolio/common/js/imagesloaded.pkgd.min.js"></script>
<script src="/portfolio/common/js/jquery.magnific-popup.min.js"></script>
<script src="/portfolio/common/js/jquery.datetimepicker.js"></script>
<script src="/portfolio/common/js/isotope.pkgd.min.js"></script>
<script type="text/javascript" src="/portfolio/common/js/common.js"></script>